Default: &defaults
  database: hithub.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hithub_test.sqlite3
  <<: *defaults

Staging:
  database: hithub_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hithub_production.sqlite3
  poolsize: 100
  <<: *defaults
