Default: &defaults
  database: hitweb.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hitweb_test.sqlite3
  <<: *defaults

Staging:
  database: hitweb_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hitweb_production.sqlite3
  poolsize: 100
  <<: *defaults
